Edit Page Additions
hmcc-global/hmccaa-web pull request #205
Opened 2024-03-09 21:07 UTC by thedomcab

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/061e6a59-9d61-4aea-b7bd-41ee54ab898b)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/3200c249-d520-485c-bb1f-9bc56814005f)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/5ec4e6df-00eb-4a9e-8b7b-beac3afc9223)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/c0819a3c-ce48-4f4a-a859-8c6a86ab533e)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/d9038cbc-9b75-4f66-ab1e-9d5c1db28908)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/380a9b72-de69-4fa4-8443-1cb95e2cc7c7)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/9b67194d-8de9-4555-9cc5-e50836230798)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/354084dc-e190-43d2-a355-5997d04e18ce)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/9030e11e-07d3-40a5-9b87-7c41c619c8df)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/73329e3c-8892-4916-b5f0-e53916ef6cbc)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/9b1ba42a-c5a3-4bfe-97a4-28d31f205eeb)

<img src="https://github.com/hmcc-global/hmccaa-web/assets/9808478/40a28c40-df46-409d-9256-644e98538ad3" width="400" />

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/89530ce2-7715-4e2b-9324-d83760588d17)

<img src="https://github.com/hmcc-global/hmccaa-web/assets/9808478/858932ee-9246-481c-98a4-4e37a9187326" width="400" />

2024-03-18 19:57 UTC, terrianx commented on frontend/src/components/page-connect/common-questions.js
<img width="1315" alt="Screenshot 2024-03-18 at 3 56 48 PM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/c0462073-0429-421f-bfec-15a30db782c0">
using chrome, i dont think this section is centered. it is on the figma

2024-03-18 20:00 UTC, thedomcab commented on frontend/src/components/page-connect/common-questions.js
will look at later

2024-03-25 20:14 UTC, terrianx commented on frontend/src/components/page-main/getinvolved.js
life group and member links are not updated.

2024-03-25 20:16 UTC, terrianx commented on frontend/src/pages/next-steps/membership.js
become a member and read more on distinctives links are not updated

2024-03-25 20:21 UTC, terrianx commented on frontend/src/pages/next-steps/baptism.js
sign up for class link not updated. 

at certain screen width image becomes unreasonably small
<img width="728" alt="Screenshot 2024-03-25 at 4 20 25 PM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/d2e41f3d-0d5b-4316-a025-80783c305b98">

2024-03-25 20:27 UTC, terrianx commented on frontend/src/pages/next-steps/ministryteams.js
> +                  about yourself and how you can be used for God&paos;s Kingdom.
typo with apostrophe unicode

<img width="579" alt="Screenshot 2024-03-25 at 4 27 13 PM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/ed6786d8-1e5c-4f56-8460-93bf5f77e38c">

2024-03-25 20:27 UTC, terrianx commented on frontend/src/pages/next-steps/ministryteams.js
> +                *Note that you must be an active member opf HMCC to serve.
extra 'p' before the f

2024-03-25 20:29 UTC, terrianx commented on frontend/src/pages/next-steps/transformation.js
> +                  Sign Up Now
no sign up link

2024-03-25 20:31 UTC, terrianx requested changes
small fixes with some links and image sizes (not sure if image problems are that important, purely visual preference). also a couple of typos

2024-03-30 19:32 UTC, thedomcab commented on frontend/src/pages/next-steps/membership.js
where should become a member link to?

2024-03-30 19:35 UTC, thedomcab commented on frontend/src/pages/next-steps/baptism.js
same here where should baptism link to?

2024-03-31 19:53 UTC, terrianx commented on frontend/src/pages/next-steps/membership.js
not sure actually, we can wait for maples response in the teams chat

2024-03-31 20:01 UTC, terrianx commented
dom its pretty much ready to merged in, just waiting on maple to get back on the links

2024-04-09 05:25 UTC, terrianx approved these changes

2024-04-09 12:00 UTC, merged