Changed LG signup link to /next-steps/lifegroups
hmcc-global/hmccaa-web pull request #214
Opened 2024-04-01 19:37 UTC by Normanwqn

If I understood issue #182 correctly, I changed the Google Form URL to `/next-steps/lifegroups` aka the lifegroup page.

2024-04-01 19:47 UTC, terrianx approved these changes

2024-04-01 19:50 UTC, terrianx requested changes
i think it should be an internal link. currently with the href it opens a new tab. use "to" param instead of href. i think it should be consistent with the other links on the 404 page that are internal.

2024-04-01 21:41 UTC, Normanwqn commented
> i think it should be an internal link. currently with the href it opens a new tab. use "to" param instead of href. i think it should be consistent with the other links on the 404 page that are internal.

Updated to `to`

2024-04-02 00:56 UTC, thedomcab approved these changes

2024-04-02 05:51 UTC, terrianx approved these changes

2024-04-04 01:55 UTC, merged